namespace CrimeMovies.Interfaces
{
    public interface IMovieService
    {
        /// <summary>
        /// Creates tasks to call the rubicon movie api, tasks get generated by dividing the amount given by the max amount items return by the api.
        /// </summary>
        /// <param name="genre"></param>
        /// <param name="amount"></param>
        /// <returns>list of Movies</returns>
        Task<List<Movie>> GetMoviesByGenre(string genre, int amount);

        /// <summary>
        /// Groups the movies by year released and orders the movies in the grouped years based on rating 
        /// </summary>
        /// <param name="movies"></param>
        /// <returns>Grouped movies based on year and sorted by ratings</returns>
        IEnumerable<(string year, IOrderedEnumerable<Movie> movies)> GroupAndOrderMovies(List<Movie> movies);
    }
}
